version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root
    secrets:
      - mongo_root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:${MONGO_ROOT_PW}@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo_express_user
    secrets:
      - mongo_express_user

volumes:
  mongo:

secrets:
  mongo_root:
    file: ./dockersecrets/mongo_root.txt
  mongo_express_user:
    file: ./dockersecrets/mongo_express_user.txt
